addons:
  artifacts:
    debug: true
    paths:
    - libs.zip
    - build.zip
    - testbuild.zip
    target_paths: 0f23ea96-bf15-4c27-b78d-2a9ec57459fd
after_success:
- ./df-build.sh
cache:
  directories:
  - $HOME/.m2
env: MAVEN_OPTS=" -Xmx2048m -Xms768m -XX:MaxPermSize=512m"
jdk:
- oraclejdk8
language: java
script: mvn clean test
# Modified by Insights Service at 2016-06-09 11:14:42.406710
